package com.cuyer.rusthub.common

class CountryMapper {

    private val countryToContinentMap = mapOf(
        "af" to "Asia",
        "al" to "Europe",
        "dz" to "Africa",
        "as" to "Australia/Oceania",
        "ad" to "Europe",
        "ao" to "Africa",
        "ai" to "North America",
        "aq" to "Antarctica",
        "ag" to "North America",
        "ar" to "South America",
        "am" to "Asia",
        "aw" to "North America",
        "au" to "Australia/Oceania",
        "at" to "Europe",
        "az" to "Asia",
        "bs" to "North America",
        "bh" to "Asia",
        "bd" to "Asia",
        "bb" to "North America",
        "by" to "Europe",
        "be" to "Europe",
        "bz" to "North America",
        "bj" to "Africa",
        "bm" to "North America",
        "bt" to "Asia",
        "bo" to "South America",
        "bq" to "North America",
        "ba" to "Europe",
        "bw" to "Africa",
        "bv" to "Antarctica",
        "br" to "South America",
        "io" to "Asia",
        "bn" to "Asia",
        "bg" to "Europe",
        "bf" to "Africa",
        "bi" to "Africa",
        "cv" to "Africa",
        "kh" to "Asia",
        "cm" to "Africa",
        "ca" to "North America",
        "ky" to "North America",
        "cf" to "Africa",
        "td" to "Africa",
        "cl" to "South America",
        "cn" to "Asia",
        "cx" to "Asia",
        "cc" to "Asia",
        "co" to "South America",
        "km" to "Africa",
        "cg" to "Africa",
        "cd" to "Africa",
        "ck" to "Australia/Oceania",
        "cr" to "North America",
        "ci" to "Africa",
        "hr" to "Europe",
        "cu" to "North America",
        "cw" to "North America",
        "cy" to "Asia",
        "cz" to "Europe",
        "dk" to "Europe",
        "dj" to "Africa",
        "dm" to "North America",
        "do" to "North America",
        "ec" to "South America",
        "eg" to "Africa",
        "sv" to "North America",
        "gq" to "Africa",
        "er" to "Africa",
        "ee" to "Europe",
        "et" to "Africa",
        "fk" to "South America",
        "fo" to "Europe",
        "fj" to "Australia/Oceania",
        "fi" to "Europe",
        "fr" to "Europe",
        "gf" to "South America",
        "pf" to "Australia/Oceania",
        "tf" to "Antarctica",
        "ga" to "Africa",
        "gm" to "Africa",
        "ge" to "Asia",
        "de" to "Europe",
        "gh" to "Africa",
        "gi" to "Europe",
        "gr" to "Europe",
        "gl" to "North America",
        "gd" to "North America",
        "gp" to "North America",
        "gu" to "Australia/Oceania",
        "gt" to "North America",
        "gg" to "Europe",
        "gn" to "Africa",
        "gw" to "Africa",
        "gy" to "South America",
        "ht" to "North America",
        "hm" to "Antarctica",
        "va" to "Europe",
        "hn" to "North America",
        "hk" to "Asia",
        "hu" to "Europe",
        "is" to "Europe",
        "in" to "Asia",
        "id" to "Asia",
        "ir" to "Asia",
        "iq" to "Asia",
        "ie" to "Europe",
        "im" to "Europe",
        "il" to "Asia",
        "it" to "Europe",
        "jm" to "North America",
        "jp" to "Asia",
        "je" to "Europe",
        "jo" to "Asia",
        "kz" to "Asia",
        "ke" to "Africa",
        "ki" to "Australia/Oceania",
        "kp" to "Asia",
        "kr" to "Asia",
        "kw" to "Asia",
        "kg" to "Asia",
        "la" to "Asia",
        "lv" to "Europe",
        "lb" to "Asia",
        "ls" to "Africa",
        "lr" to "Africa",
        "ly" to "Africa",
        "li" to "Europe",
        "lt" to "Europe",
        "lu" to "Europe",
        "mo" to "Asia",
        "mk" to "Europe",
        "mg" to "Africa",
        "mw" to "Africa",
        "my" to "Asia",
        "mv" to "Asia",
        "ml" to "Africa",
        "mt" to "Europe",
        "mh" to "Australia/Oceania",
        "mq" to "North America",
        "mr" to "Africa",
        "mu" to "Africa",
        "yt" to "Africa",
        "mx" to "North America",
        "fm" to "Australia/Oceania",
        "md" to "Europe",
        "mc" to "Europe",
        "mn" to "Asia",
        "me" to "Europe",
        "ms" to "North America",
        "ma" to "Africa",
        "mz" to "Africa",
        "mm" to "Asia",
        "na" to "Africa",
        "nr" to "Australia/Oceania",
        "np" to "Asia",
        "nl" to "Europe",
        "nc" to "Australia/Oceania",
        "nz" to "Australia/Oceania",
        "ni" to "North America",
        "ne" to "Africa",
        "ng" to "Africa",
        "nu" to "Australia/Oceania",
        "nf" to "Australia/Oceania",
        "mp" to "Australia/Oceania",
        "no" to "Europe",
        "om" to "Asia",
        "pk" to "Asia",
        "pw" to "Australia/Oceania",
        "ps" to "Asia",
        "pa" to "North America",
        "pg" to "Australia/Oceania",
        "py" to "South America",
        "pe" to "South America",
        "ph" to "Asia",
        "pn" to "Australia/Oceania",
        "pl" to "Europe",
        "pt" to "Europe",
        "pr" to "North America",
        "qa" to "Asia",
        "re" to "Africa",
        "ro" to "Europe",
        "ru" to "Europe",
        "rw" to "Africa",
        "bl" to "North America",
        "sh" to "Africa",
        "kn" to "North America",
        "lc" to "North America",
        "mf" to "North America",
        "pm" to "North America",
        "vc" to "North America",
        "ws" to "Australia/Oceania",
        "sm" to "Europe",
        "st" to "Africa",
        "sa" to "Asia",
        "sn" to "Africa",
        "rs" to "Europe",
        "sc" to "Africa",
        "sl" to "Africa",
        "sg" to "Asia",
        "sx" to "North America",
        "sk" to "Europe",
        "si" to "Europe",
        "sb" to "Australia/Oceania",
        "so" to "Africa",
        "za" to "Africa",
        "gs" to "Antarctica",
        "ss" to "Africa",
        "es" to "Europe",
        "lk" to "Asia",
        "sd" to "Africa",
        "sr" to "South America",
        "sj" to "Europe",
        "sz" to "Africa",
        "se" to "Europe",
        "ch" to "Europe",
        "sy" to "Asia",
        "tw" to "Asia",
        "tj" to "Asia",
        "tz" to "Africa",
        "th" to "Asia",
        "tl" to "Asia",
        "tg" to "Africa",
        "tk" to "Australia/Oceania",
        "to" to "Australia/Oceania",
        "tt" to "North America",
        "tn" to "Africa",
        "tr" to "Asia",
        "tm" to "Asia",
        "tc" to "North America",
        "tv" to "Australia/Oceania",
        "ug" to "Africa",
        "ua" to "Europe",
        "ae" to "Asia",
        "gb" to "Europe",
        "us" to "North America",
        "um" to "Australia/Oceania",
        "uy" to "South America",
        "uz" to "Asia",
        "vu" to "Australia/Oceania",
        "ve" to "South America",
        "vn" to "Asia",
        "vg" to "North America",
        "vi" to "North America",
        "wf" to "Australia/Oceania",
        "eh" to "Africa",
        "ye" to "Asia",
        "zm" to "Africa",
        "zw" to "Africa"
    )

    fun getContinentFromCountryCode(countryCode: String): String? {
        return countryToContinentMap[countryCode]
    }
}